name: $(Build.DefinitionName)_$(SourceBranchName)_$(BuildNumber)

trigger:
- main
- release/1.x

pool:
  vmImage: 'windows-2019'

variables:
  BuildNumber: $[counter()]
  ${{ if contains( variables['Build.SourceBranch'], 'release/' ) }}:
    UseSuffix: false

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    arguments: -c Release
    projects: |
      src\**\Microsoft.Azure.WebJobs.Extensions.ApplicationInsights.csproj
- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
  displayName: 'ESRP CodeSigning'
  inputs:
    ConnectedServiceName: 'ESRP Service'
    UseMinimatch: true
    FolderPath: 'src\'
    Pattern: |
      bin\Release\**\Microsoft.Azure.WebJobs.Extensions.ApplicationInsights.dll
    signConfigType: inlineSignParams
    inlineOperation: |
        [
          {
            "KeyCode": "CP-230012",
            "OperationCode": "SigntoolSign",
            "Parameters": {
              "OpusName": "Microsoft",
              "OpusInfo": "http://www.microsoft.com",
              "FileDigest": "/fd \"SHA256\"",
              "PageHash": "/NPH",
              "TimeStamp": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            },
            "ToolName": "sign",
            "ToolVersion": "1.0"
          },
          {
            "KeyCode": "CP-230012",
            "OperationCode": "SigntoolVerify",
            "Parameters": {},
            "ToolName": "sign",
            "ToolVersion": "1.0"
          }
        ]
- task: DotNetCoreCLI@2
  displayName: 'Pack'
  inputs:
    command: 'custom'
    custom: 'pack'
    arguments: '--no-build -c Release -o artifacts'
    projects: |
      **\Microsoft.Azure.WebJobs.Extensions.ApplicationInsights.csproj
- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
  displayName: 'ESRP CodeSigning: Nupkg'
  inputs:
    ConnectedServiceName: 'ESRP Service'
    FolderPath: 'artifacts'
    Pattern: 'Microsoft.Azure.WebJobs.Extensions.ApplicationInsights*.nupkg'
    signConfigType: inlineSignParams
    inlineOperation: |
      [
          {
            "KeyCode": "CP-401405",
            "OperationCode": "NuGetSign",
            "Parameters": {},
            "ToolName": "sign",
            "ToolVersion": "1.0"
          },
          {
            "KeyCode": "CP-401405",
            "OperationCode": "NuGetVerify",
            "Parameters": {},
            "ToolName": "sign",
            "ToolVersion": "1.0"
          }
      ]
- pwsh: |
    Move-Item -Path '$(Build.Repository.LocalPath)\artifacts\Microsoft.Azure.WebJobs.Extensions.ApplicationInsights.*' -Destination '$(Build.ArtifactStagingDirectory)'
  displayName: 'Move artifacts'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'